### PR TITLE
added lockfile

### PR DESCRIPTION
**Pull request by mees-**

### CODE REVIEW

**Comment by jamen** [comment]
Question: Will we have to update this lockfile every time we change dependencies?

**Comment by mees-** [comment]
@jamen I think so yeah

**Comment by bdbch** [comment]
@mees- 
You want to move over to yarn? What's the difference or pros for yarn? Didn't checked it out yet.

**Comment by mees-** [comment]
Yarn is pretty quick compared to npm, it works with the npm registry and we don't necessarily have to make a choice, you can use whichever you like. yarn automatically generates a lockfile which should be checked in though, its the same as `npm shrinkwrap`

**Review by jamen — APPROVED** [review]

**Pull request merged**
