### PR TITLE
Factory

### PR DESCRIPTION
**Pull request by jamen**
NOT READY FOR MERGE: Still working on this.  But it would be cool to get some feedback so far.

I've done a background process system, where you can control it via the CLI:

```
$ cordlr --start              
Successfully started.     

$ cordlr --start              
Error: PID file exists (Bot is already running)
```

```
$ cordlr --restart            
Successfully restarted.
```

```
$ cordlr --stop               
Successfully stopped.                          
```

I also took a stab at structuring the command system, however I haven't tested it in chat yet.

### CODE REVIEW

**Comment by bdbch** [comment]
good idea. would it be globally installed or just accessible from the botfolder?

**Comment by jamen** [comment]
Globally installed, then you create a `.cordlrrc.json` file (or many other options using [`rc`](https://npmjs.com/packages/rc)) to configure it.

Currently there is only "prefix":

``` js
{
  "prefix": "~"
}
```

**Comment by bdbch** [comment]
Could be a thing but I think for now we should focus on the main bot functionality. Anyway nice idea, we'll see how we can implement it into our bot. @Devcord/developers what do you think?

**Comment by turbits** [comment]
Looks good bud :+1: nice work. Don't like multi-line comments? (in clear.js, lines 4-6) :smile:

**Comment by jamen** [comment]
Thanks.

I do like multi-line comments for JSdoc-like style:

``` js
/**
 * Description here.
 * blah blah
 */

// or

/** Desctipion here.
  * blah blah.
  */
```

I just figured we would delete those `clear.js` comments later.

Also, I have everything cleaned up more locally, just making osme more changes, then I'll merge.

**Comment by jamen** [comment]
Ready to merge!

**Comment by jamen** [comment]
Actually, let me write some docs for this first, on how to use the configuration

**Comment by jamen** [comment]
Done.  @Devcord/community-member can we merge this now?

**Comment by jamen** [comment]
Docs could use improvements, but that is for a later PR.  Not sure how I want to organize it.

**Comment by goonit** [comment]
What purpose would having our own cli serve over using a service like pm2, nodemon or forever?

**Comment by jamen** [comment]
The `background.js` was for fun, and it works well.  I did consider using `forever-monitor` or `pm2`, but this is simple and built into the CLI flow that we will have, so it looks nice.

I think people who don't program would find it useful, because they might not know what those are, or how to even create background processes, so this does it for them.

**Comment by Hammster** [comment]
Btw: we are going to host it on my public dedicated servers, they are optimized for pm2 with additional monitoring and mongodb cluster and failover.

But IMHO the background.js is a good thing and we should keep it as optional, but maybe educating people to use pm2, nodeamon or forever-monitor for production use is better then giving them a shortcut. :smile:

**Pull request merged**
